server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8002/api/products
          predicates:
            - Path=/api/products/**
        - id: orders
          uri: http://localhost:8002/api/orders
          predicates:
            - Path=/api/orders/**