server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: trading-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:11001/jshop?currentSchema=public&user=postgres&password=1212
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml